/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportedListingsRouteImport } from './routes/admin/reported-listings'
import { Route as AdminRejectedListingsRouteImport } from './routes/admin/rejected-listings'
import { Route as AdminPendingAdsRouteImport } from './routes/admin/pending-ads'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLiveListingsRouteImport } from './routes/admin/live-listings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminChatMonitoringRouteImport } from './routes/admin/chat-monitoring'
import { Route as AdminActionLogsRouteImport } from './routes/admin/action-logs'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AdminListingsTypeRouteImport } from './routes/admin/listings/$type'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportedListingsRoute = AdminReportedListingsRouteImport.update({
  id: '/reported-listings',
  path: '/reported-listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRejectedListingsRoute = AdminRejectedListingsRouteImport.update({
  id: '/rejected-listings',
  path: '/rejected-listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPendingAdsRoute = AdminPendingAdsRouteImport.update({
  id: '/pending-ads',
  path: '/pending-ads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLiveListingsRoute = AdminLiveListingsRouteImport.update({
  id: '/live-listings',
  path: '/live-listings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatMonitoringRoute = AdminChatMonitoringRouteImport.update({
  id: '/chat-monitoring',
  path: '/chat-monitoring',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActionLogsRoute = AdminActionLogsRouteImport.update({
  id: '/action-logs',
  path: '/action-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminListingsTypeRoute = AdminListingsTypeRouteImport.update({
  id: '/listings/$type',
  path: '/listings/$type',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/action-logs': typeof AdminActionLogsRoute
  '/admin/chat-monitoring': typeof AdminChatMonitoringRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/live-listings': typeof AdminLiveListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pending-ads': typeof AdminPendingAdsRoute
  '/admin/rejected-listings': typeof AdminRejectedListingsRoute
  '/admin/reported-listings': typeof AdminReportedListingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/listing/$id': typeof ListingIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/admin/listings/$type': typeof AdminListingsTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sell': typeof AuthenticatedSellRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/action-logs': typeof AdminActionLogsRoute
  '/admin/chat-monitoring': typeof AdminChatMonitoringRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/live-listings': typeof AdminLiveListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pending-ads': typeof AdminPendingAdsRoute
  '/admin/rejected-listings': typeof AdminRejectedListingsRoute
  '/admin/reported-listings': typeof AdminReportedListingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/listing/$id': typeof ListingIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/admin/listings/$type': typeof AdminListingsTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/action-logs': typeof AdminActionLogsRoute
  '/admin/chat-monitoring': typeof AdminChatMonitoringRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/live-listings': typeof AdminLiveListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pending-ads': typeof AdminPendingAdsRoute
  '/admin/rejected-listings': typeof AdminRejectedListingsRoute
  '/admin/reported-listings': typeof AdminReportedListingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/listing/$id': typeof ListingIdRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/admin/listings/$type': typeof AdminListingsTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/help'
    | '/search'
    | '/chat'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/admin/action-logs'
    | '/admin/chat-monitoring'
    | '/admin/dashboard'
    | '/admin/live-listings'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/pending-ads'
    | '/admin/rejected-listings'
    | '/admin/reported-listings'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/reset-password'
    | '/listing/$id'
    | '/chat/$id'
    | '/admin/listings/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/help'
    | '/search'
    | '/chat'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/admin/action-logs'
    | '/admin/chat-monitoring'
    | '/admin/dashboard'
    | '/admin/live-listings'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/pending-ads'
    | '/admin/rejected-listings'
    | '/admin/reported-listings'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/reset-password'
    | '/listing/$id'
    | '/chat/$id'
    | '/admin/listings/$type'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/help'
    | '/search'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/sell'
    | '/_authenticated/wishlist'
    | '/admin/action-logs'
    | '/admin/chat-monitoring'
    | '/admin/dashboard'
    | '/admin/live-listings'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/pending-ads'
    | '/admin/rejected-listings'
    | '/admin/reported-listings'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/reset-password'
    | '/listing/$id'
    | '/_authenticated/chat/$id'
    | '/admin/listings/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  SearchRoute: typeof SearchRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reported-listings': {
      id: '/admin/reported-listings'
      path: '/reported-listings'
      fullPath: '/admin/reported-listings'
      preLoaderRoute: typeof AdminReportedListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rejected-listings': {
      id: '/admin/rejected-listings'
      path: '/rejected-listings'
      fullPath: '/admin/rejected-listings'
      preLoaderRoute: typeof AdminRejectedListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pending-ads': {
      id: '/admin/pending-ads'
      path: '/pending-ads'
      fullPath: '/admin/pending-ads'
      preLoaderRoute: typeof AdminPendingAdsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/live-listings': {
      id: '/admin/live-listings'
      path: '/live-listings'
      fullPath: '/admin/live-listings'
      preLoaderRoute: typeof AdminLiveListingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chat-monitoring': {
      id: '/admin/chat-monitoring'
      path: '/chat-monitoring'
      fullPath: '/admin/chat-monitoring'
      preLoaderRoute: typeof AdminChatMonitoringRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/action-logs': {
      id: '/admin/action-logs'
      path: '/action-logs'
      fullPath: '/admin/action-logs'
      preLoaderRoute: typeof AdminActionLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/listings/$type': {
      id: '/admin/listings/$type'
      path: '/listings/$type'
      fullPath: '/admin/listings/$type'
      preLoaderRoute: typeof AdminListingsTypeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminActionLogsRoute: typeof AdminActionLogsRoute
  AdminChatMonitoringRoute: typeof AdminChatMonitoringRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLiveListingsRoute: typeof AdminLiveListingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPendingAdsRoute: typeof AdminPendingAdsRoute
  AdminRejectedListingsRoute: typeof AdminRejectedListingsRoute
  AdminReportedListingsRoute: typeof AdminReportedListingsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminListingsTypeRoute: typeof AdminListingsTypeRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActionLogsRoute: AdminActionLogsRoute,
  AdminChatMonitoringRoute: AdminChatMonitoringRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLiveListingsRoute: AdminLiveListingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPendingAdsRoute: AdminPendingAdsRoute,
  AdminRejectedListingsRoute: AdminRejectedListingsRoute,
  AdminReportedListingsRoute: AdminReportedListingsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminListingsTypeRoute: AdminListingsTypeRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  SearchRoute: SearchRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
